# TODO : If you have ports, uncomment this file and add them to the ports spec
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}
#   labels:
#     app: {{ template "template.name" . }}
#     chart: {{ template "template.chart" . }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 8080
#       name: http
#     - port: 443
#       targetPort: 8443
#       name: https
#   selector:
#     app: {{ template "template.name" . }}
#     release: {{ .Release.Name }}

