# TODO : If you have ports, uncomment this file and add them to the ports spec
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: port8080
    - port: 8443
      targetPort: 8443
      name: port8443
  selector:
    app: {{ template "template.name" . }}
    release: {{ .Release.Name }}

